export const GET_CRYPTO_REQUEST = 'GET_CRYPTO_REQUEST'
export const GET_CRYPTO_SUCCESS = 'GET_CRYPTO_SUCCESS'
export const GET_SINGLE_CRYPTO_SUCCESS = 'GET_SINGLE_CRYPTO_SUCCESS'
export const GET_CRYPTO_FAILURE = 'GET_CRYPTO_FAILURE'
